---
title: "Untitled"
output: html_document
---

#Problem 1  
```{r first}

library(tidyverse)
library(p8105.datasets)


brfss_smart2010
#load the file from git,then limit the response into Excellent to Poor#
file=brfss_smart2010 %>%
  select(-Class,-Topic,-Question,-Sample_Size,-Confidence_limit_Low:-GeoLocation)%>%
  filter(Response%in%c("Excellent","Very good","Good","Fair","Poor"))%>%
  spread(key=Response,value=Data_value)
gitfile=na.omit(file)
gitfile
x=filter(gitfile,Locationabbr=="NY")
x

  

gitfile2002=filter(gitfile,Year==2002)
count(gitfile2002,Locationabbr)

gitfile %>%
  group_by(Year, Locationabbr) %>%
  summarize(n_obs = n())%>%
  ggplot(aes(x = Year, y = n_obs, color = Locationabbr)) + 
    geom_point() + geom_line() + 
    theme(legend.position = "bottom")

  
gitfile %>%
  group_by(Year, Locationdesc) %>%
  filter(Locationabbr=="NY",Year%in%c(2002,2006,2010))%>%
  summarize(mean_ex = mean(Excellent,na.rm=TRUE)) %>% 
  
  knitr::kable(digits = 1)
             
```
*After listing the freq of Locationabbr, the state CT,FL and NC have 7 locations.


#Problem 2
```{r second}
library(tidyverse)
library(p8105.datasets)

instacart
new=select(instacart,product_name,order_number,aisle,order_dow,order_hour_of_day)
count_aisle=distinct(instacart,aisle)
count_aisle
number_aisle=count(instacart,aisle)
arrange_aisle=arrange(number_aisle,desc(n))
arrange_aisle

ggplot(number_aisle, aes(x = aisle, y = n)) + 
  geom_point()+
  theme(axis.title.x=element_blank(),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank())

baking_ingredients=filter(new,aisle=="baking ingredients")
baking_ingredients%>%
  group_by(product_name) %>%
  summarize(sumnum = sum(order_number)) %>% 
  spread(key = product_name, value = sumnum) %>% 
  knitr::kable(digits = 1)
dog_food_care=filter(new,aisle=="dog food care")
dog_food_care%>%
  group_by(product_name) %>%
  summarize(sumnum = sum(order_number)) %>% 
  spread(key = product_name, value = sumnum) %>% 
  knitr::kable(digits = 1)
packaged_vegetables_fruits=filter(new,aisle=="packaged vegetables fruits")
packaged_vegetables_fruits%>%
  group_by(product_name) %>%
  summarize(sumnum = sum(order_number)) %>% 
  spread(key = product_name, value = sumnum) %>% 
  knitr::kable(digits = 1)
baking=c("Light Brown Sugar")
dog=c("Standard Size Pet Waste bags")
packaged=c("Organic Baby Spinach")
df1=data_frame(baking,dog,packaged)
df1
last=filter(new,product_name%in%c("Pink Lady Apples","Coffee Ice Cream"))
last%>%
  group_by(product_name,order_dow)%>%
  summarize(mean=mean(order_hour_of_day))%>%
  spread(key=order_dow,value=mean)%>%
  knitr::kable(digits = 1)
          
```


* The data has 1384607 rows and 15 columns (variables) with column names product id, user id, order hours a day, days since prior order, order number and so on. 
* There are 134 different aisles, and the fresh vegetable aisle has the most items ordered from. 
